language: python

python:
    - "2.7"

virtualenv:
  system_site_packages: true

before_install:
    - bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
    - # Add MCRInstaller.bin dependencies first
    - sudo apt-get install -y libxp6 libxpm4 libxmu6 libxt6 bc
    - source continuous_integration/setup_spm.sh
    - sudo apt-get install -qq python-scipy python-nose python-nibabel python-sklearn python-sympy python-networkx python-nipy python-nipype
    - sudo apt-get install -qq python-pip
    - pip install "nilearn>=0.1.3"
    - pip install coverage coveralls

install:
    - python setup.py install

script:
    - make clean
    - make test-code
    - python examples/nipype_preproc_spm_auditory.py

after_success:
    - coveralls
