language: python

python:
    - "2.7"

virtualenv:
  system_site_packages: true

before_install:
    - bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
    - sudo apt-get install -qq python-scipy python-nose python-nibabel python-sklearn python-sympy python-networkx python-nipy python-nipype
    - sudo apt-get install -qq python-pip
    - pip install "nilearn>=0.1.3"
    - pip install coverage coveralls
    - source continuous_integration/setup_spm.sh

install:
    - python setup.py install

script:
    - make clean
    - make test-code
    - export PYTHONPATH=$PWD; python examples/nipype_preproc_spm_auditory.py

after_success:
    - coveralls
